version : "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - blog-postgres:/var/lib/postgresql/data/

    ports:
      - 5432:5432
      
    env_file:
      - .env

  blog:
    container_name : blog
    restart: always
    build: .
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./:/app
      - static_volume:/app/static
      - media_volume:/app/media

    env_file:
      - .env

    expose:
      - "8000"
    
    depends_on:
      - postgres

  nginx:

    image: nginx

    container_name: nginx

    restart: always

    ports: 

      - "80:80"

    volumes:

      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media

volumes:
  blog-postgres:
  static_volume:
  media_volume: