version : 3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - blog-postgres:/var/lib/postgresql/data/

    ports:
      - 5432:5432
      
    env_file:
      - .env


  blog:
    container_name : blog
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "587:587"
      - "465:465"

    env_file:
      - .env

    expose:
      - 587
      - 25
      - 465
    
    depends_on:
      - postgres





volumes:
  blog-postgres: