# Generated by Django 5.1.1 on 2024-10-18 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SiteSetting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="additional_descriptions",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="copy_right_text",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="descriptions",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="email2",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="image1",
            field=models.ImageField(default=1, upload_to="SiteSetting/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="image2",
            field=models.ImageField(default=1, upload_to="SiteSetting/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="location_link",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="logo",
            field=models.ImageField(default=1, upload_to="logo/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="phone_number",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="second_number",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="short_about",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="short_addr",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="website_title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
