# Generated by Django 5.1.1 on 2024-10-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0004_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
