# Generated by Django 5.1.1 on 2024-10-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSetting', '0005_sitesetting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_read_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
