# Generated by Django 5.1.1 on 2024-11-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_verified_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified_code',
            field=models.CharField(default='hV4eOmAOHT0tFeKBqx7TEQRZUGjV8tui05YJSpPAb3GZHm49SkGRBlW2rRYnbDucfmb7bc1kmHd5hlIAIj0cmewfdhM7vjTEkG5eb4N9Ytuw4CptxurxXar7FED41r03zY17AonFhhb6oJj7GDv80zAj8yWiEBHC4xApYVIQRIr45FAHbIau0gZIO8G9TLlgsEfCuiauJYLkDgXx3uleytOy9vK0vug8Z7q2etVYmO5Bf9OPu2I9GK42xBxvwlj', max_length=255),
        ),
    ]
