# Generated by Django 5.1.1 on 2024-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_user_verified_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified_code",
            field=models.CharField(
                default="5DL1FaBKSwHfCBd7feQkkR6QrUc0T87h1Fkh0fl9BrXOjSHvZ9JxnY6CqoCYWnF1u1SWKQkyzFzDBHv23LKvMbYKYZy74iz7rxAfvZ9QowJcQ42n4SsPdNvURLkjj7BArObBwdZkgE2EmAwRR9kmwbh8oZ9LkjFAHs3AK2ILnZkX387CaiWlBizt7g2LwRicK6XsDnOa6olOty4SgBlDT58uwnQF0BlsUCEzS6bS2Df513xYuhYK32nGknPni2q",
                max_length=255,
            ),
        ),
    ]
