# Generated by Django 5.1.1 on 2024-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_user_verified_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified_code",
            field=models.CharField(
                default="hqLENpoJnOLXXrlL3cqSSnqOhG7ihcHoIz9WfRLof2w4X4vBZCZGAMPqJXHB2i8Wfipc0Wr4oIB1OkBOPucu6tuA80CxlBU90kjZnpReg6iJmeKU8TWMR9qPhCSMiPVgq7vkYKQnHLVUgZWwjdC1sn4pJo0JeF0IAxbQDopuZS0np3kNuLGcQV1cgwN25NLy9f26TFwiC03Xm4zDW60tDCjzizkV3tVVZ2ijYHurnOQjIwa0612g4bpw86kEVPj",
                max_length=255,
            ),
        ),
    ]
