# Generated by Django 5.1.1 on 2024-11-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_user_verified_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified_code",
            field=models.CharField(
                default="HFOmLeJnPB9UnKOQviUwFsjk7V4vygngU59EUpNq6Vn6jdEsjFfj1NoSLNukmCUsRisy9RZtv4hR67YA3K3gUVDl3FO4gXRiFPhLEzpctcgKMcGjRnCIDzKBPaZO1OR1LwpohNjtISMSqfEhNVDnC7Mk9tAEKAaVouCuAiSa4AgeMimo1TMIUedy8r919zDxZYeUTvXM5LcC91HYgtAKb1jxsVnrTvcKJHJ4sV98d8GPOm0EjeFhblkb7Uh1hzf",
                max_length=255,
            ),
        ),
    ]
