# Generated by Django 5.1.1 on 2024-11-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_alter_user_verified_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified_code",
            field=models.CharField(
                default="XKINUlPCZQPM29fFhxreShpfOXlgbdVaH5jC97UpSbWpJEMGwEo42eZyAspXeswahfF2cXKxs5FsMVYg9kPSFrgL0CoFJKPGSNhxZMiGR3nO6aCECZhdaeJwkleFzoUcJ1WUwXa9x0dLLTJxuQNidqV2TaeorhLs49tbrqssZJFGaDWtPs4jORm6cboaPQzr5h0kJ4nwvBYA07qqX4k3yrxXHe7DYlZ4dU99wbG1clG8WJITyQSz941BN6Zc68g",
                max_length=255,
            ),
        ),
    ]
