# Generated by Django 5.1.1 on 2024-11-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_user_verified_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified_code",
            field=models.CharField(
                default="U3Nxd9sDfb3u0UgKANrCvbz2PCKObeQ6FijKpdBVhBUggJQmUvX1SFG8fjsxZTv3iV59zsgiZD2PxkwrxBOTmivTMSfNN5f8UWf7gEB3jpOIQqsvMikjVmbuncq2dCpuFzuLRS9q1sp83xj7sk9asYPGdRDEYaeQBkeVSpl8YFCZReJJ8u8wext0OVhDSbnyWNwEZ5TmLqYYJOfnJ54bDvKRIiicxJnmvjye8ty3jYNAimuR7xImbzLK9d4mFG3",
                max_length=255,
            ),
        ),
    ]
