# Generated by Django 5.1.1 on 2024-12-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_verified_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified_code',
            field=models.CharField(default='V3C1hmig1KCxhxBeDEEpMbjiJ4JjGH6UGBspmiu1VjpVk1pSFmgSeKKDDfO9XXSsndBBWSKP1iUZC7aHUo9BBuVVse2V1BgExMg6Y28Mp0pPlxI1iRRtuXn5OQAEIhrMLsbvfRaqIj2EnfgITURBl0tCBaiqnBYI7NnAy6vyOwmnmLE4mhsbbP9TcPB4HaSMCJ9xKYwrOj8GoWKKwBdvJSKnTXx0E4T9IpxFTmlUosmqupVUNlIZUa1Hq2FTcMV', max_length=255),
        ),
    ]
