# Generated by Django 5.1.1 on 2024-10-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
