# Generated by Django 5.1.1 on 2024-10-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
