# Generated by Django 5.1.1 on 2024-11-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_category_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
