name: ADV Blog CI/CD
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run the Docker Compose
      run: docker compose up -d
    - name: Run flake8
      run: docker compose exec blog sh -c 'flake8 .'
    - name: Run Unit Test
      run: docker compose exec blog sh -c 'python manage.py test'
    - name: Run PyTest For Testing APIs
      run: docker compose exec blog sh -c 'pytest . '

  Deploy:
    if: ${{ contains(join(needs.*.result, ','), 'success')}}
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Connect and Execute Command
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        script: |
          cd ADV_Blog
          docker compose stop
          git pull blog master
          docker compose -f docker-compose-production.yml up 
